# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
formats: all

# Set OS
build:
  os: ubuntu-22.04