#!/bin/bash

#License:
#"Remote Syslog" is a free application what can be used to view syslog messages.
#Copyright (C) 2022 Tom Slenter
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#For more information contact the author:
#Name author: Tom Slenter
#E-mail: info@remotesyslog.com

RSDEST=/opt/RS
RSBIN=/usr/bin
RSPATH=$(pwd)
RSTMP=/tmp

#Banner
function banner() {
    echo ""
    echo "##################################################"
    echo "#Remote Syslog Master Script                     #"
    echo "#More information: https://www.remotesyslog.com/ #"
    echo "#Remote Syslog installation                      #"
    echo "#Version: RSEINSTALLER 0.1                       #"
    echo "#URL/Donation: https://github.com/tslenter/RS    #"
    echo "##################################################"
    echo ""
}

#Check if user is root
if ! [ $(id -u) = 0 ]; then
    clear
    banner
    echo "This installation must be run as root!"
    echo ""
    exit 1
fi

#Check if file exist
function check_file() {
    file=$1
    if [ -e "$file" ]; then
        echo "File: $1 exists, continue installation ..."
    else
        echo "File: $1 does not exist, exit ..."
        exit
    fi
}

function rsecore() {
    echo "Download installation ..."
    git clone --branch main https://github.com/tslenter/RSECORE $RSTMP/RSECORE_GIT
    echo "Check if download is successfull ..."
    if [ -d "$RSTMP/RSECORE_GIT" ]; then
         echo "Continue installation ..."
    else
         echo "Clone not successfull ..."
         exit
    fi
    cd $RSTMP/RSECORE_GIT/
    chmod +x $RSTMP/RSECORE_GIT/rsecore
    $RSTMP/RSECORE_GIT/rsecore
    cd $RSPATH
    rm -rf $RSTMP/RSECORE_GIT
}

function rsccore() {
    echo "Download installation ..."
    git clone --branch main https://github.com/tslenter/RSCCORE $RSTMP/RSCCORE_GIT
    echo "Check if download is successfull ..."
    if [ -d "$RSTMP/RSCCORE_GIT" ]; then
         echo "Continue installation ..."
    else
         echo "Clone not successfull ..."
         exit
    fi
    cd $RSTMP/RSCCORE_GIT/
    chmod +x $RSTMP/RSCCORE_GIT/rsccore
    $RSTMP/RSCCORE_GIT/rsccore
    cd $RSPATH
    rm -rf $RSTMP/RSCCORE_GIT
}

function rseweb() {
    echo "Download installation ..."
    git clone --branch main https://github.com/tslenter/RSEWEB $RSTMP/RSEWEB_GIT
    echo "Check if download is successfull ..."
    if [ -d "$RSTMP/RSEWEB_GIT" ]; then
         echo "Continue installation ..."
    else
         echo "Clone not successfull ..."
         exit
    fi
    cd $RSTMP/RSEWEB_GIT/
    chmod +x $RSTMP/RSEWEB_GIT/rseweb
    $RSTMP/RSEWEB_GIT/rseweb
    cd $RSPATH
    rm -rf $RSTMP/RSEWEB_GIT
}

function rscweb() {
    echo "Download installation ..."
    git clone --branch main https://github.com/tslenter/RSCWEB $RSTMP/RSCWEB_GIT
    echo "Check if download is successfull ..."
    if [ -d "$RSTMP/RSCWEB_GIT" ]; then
         echo "Continue installation ..."
    else
         echo "Clone not successfull ..."
         exit
    fi
    cd $RSTMP/RSCWEB_GIT/
    chmod +x $RSTMP/RSCWEB_GIT/rscweb
    $RSTMP/RSCWEB_GIT/rscweb
    cd $RSPATH
    rm -rf $RSTMP/RSCWEB_GIT
}

function rsxweb() {
    echo "Download installation ..."
    git clone --branch main https://github.com/tslenter/RSXWEB $RSTMP/RSXWEB_GIT
    echo "Check if download is successfull ..."
    if [ -d "$RSTMP/RSXWEB_GIT" ]; then
         echo "Continue installation ..."
    else
         echo "Clone not successfull ..."
         exit
    fi
    cd $RSTMP/RSXWEB_GIT/
    chmod +x $RSTMP/RSXWEB_GIT/rsxweb
    $RSTMP/RSXWEB_GIT/rsxweb
    cd $RSPATH
    rm -rf $RSTMP/RSXWEB_GIT
}

function rslweb() {
    echo "Download installation ..."
    git clone --branch main https://github.com/tslenter/RSLWEB $RSTMP/RSLWEB_GIT
    echo "Check if download is successfull ..."
    if [ -d "$RSTMP/RSLWEB_GIT" ]; then
         echo "Continue installation ..."
    else
         echo "Clone not successfull ..."
         exit
    fi
    cd $RSTMP/RSLWEB_GIT/
    chmod +x $RSTMP/RSLWEB_GIT/rslweb
    $RSTMP/RSLWEB_GIT/rslweb
    cd $RSPATH
    rm -rf $RSTMP/RSLWEB_GIT
}

function rseinstallerremove() {
    echo "Remove rseinstaller ..."
    rm -rf $RSBIN/rseinstaller
}

#Going to the plugin menu
function addons(){
    echo "Check addons requirments ..."
    echo "The addons require the RSE Core and mostly the RSX interface ..."
    check_file $RSBIN/rseview
    echo "Plugins are experemental check configuration before installation ..."
    while true; do
    read -p "Do you wish to continue? y/n: " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
    done
    echo "Download installation ..."
    git clone --branch main https://github.com/tslenter/RSADDONS $RSTMP/RSADDONS_GIT
    echo "Check if download is successfull ..."
    if [ -d "$RSTMP/RSADDONS_GIT" ]; then
         echo "Continue installation ..."
    else
         echo "Clone not successfull ..."
         exit
    fi
    cd $RSTMP/RSADDONS_GIT/
    chmod +x $RSTMP/RSADDONS_GIT/rsaddon
    $RSTMP/RSADDONS_GIT/rsaddon
    cd $RSPATH
    rm -rf $RSTMP/RSADDONS_GIT
}

echo "Setting up environment ..."
echo "Check 1 ..."
if [ -e $RSPATH/rseinstaller ]; then
    echo "rseinstaller found in local directory, copy to $RSDEST started ..."
    if [ -d $RSDEST ]; then
        echo "Directory already exist ..."
    else
        mkdir $RSDEST
        echo "Directory created ..."
    fi
    cp -rf $RSPATH/* $RSDEST
    cp -rf $RSDEST/rseinstaller $RSBIN/rseinstaller
    chmod +x $RSBIN/rseinstaller
elif [ -e $RSDEST/rseinstaller ]; then
    echo "rseinstaller run from $RSDEST, going for $RSDEST environment ..."
else
    echo "Did you run the installer from the right directory? ..."
fi

clear
banner
#Menu
PS3='Please enter your choice: '
options=("RSE core installation" "RSC core installation" "RSC webinterface installation" "RSE webinterface installation" "RSX webinterface installation" "RSL devkit" "Addons for RSE Core or RSX" "RSEINSTALLER removal" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "RSE core installation")
            clear
            banner
            rsecore
            exit
    ;;
        "RSC core installation")
            clear
            banner
            rsccore
            exit
    ;;
        "RSC webinterface installation")
            clear
            banner
            rscweb
            exit
    ;;    
        "RSE webinterface installation")
            clear
            banner
            rseweb
            exit
    ;;
        "RSX webinterface installation")
            clear
            banner
            rsxweb
            exit
    ;;
        "RSL devkit")
            clear
            banner
            rslweb
            exit
    ;;
        "Addons for RSE Core or RSX")
            clear
            banner
            addons
            exit
    ;;
        "RSEINSTALLER removal")
            clear
            rseinstallerremove
            exit
    ;;
        "Quit")
            echo "Thank you for using Remote syslog ..."
            break
    ;;
        *) echo "Invalid option $REPLY ..." ;;
    esac
done
